import type { CallRecord, AnalyticsResponse } from "./types";

export const MOCK_AGENTS = [
  { agentId: "agent-001", agentName: "Sarah Chen" },
  { agentId: "agent-002", agentName: "Marcus Johnson" },
  { agentId: "agent-003", agentName: "Priya Patel" },
  { agentId: "agent-004", agentName: "James O'Brien" },
  { agentId: "agent-005", agentName: "Aisha Williams" },
];

export const MOCK_CALLS: CallRecord[] = [
  {
    callId: "call-001",
    timestamp: "2026-03-06T09:12:00Z",
    agentId: "agent-001",
    agentName: "Sarah Chen",
    duration: 342,
    summary: [
      "Customer called about unexpected charge of $49.99 on their monthly bill.",
      "Agent identified a duplicate subscription and issued a full refund within 5 minutes.",
      "Missed opportunity to offer loyalty discount after resolving the dispute.",
    ],
    agentScore: 8,
    improvement: "Proactively offer retention discounts after billing dispute resolutions to reduce churn risk.",
    keywords: ["refund", "billing", "duplicate", "charge", "subscription"],
    sentimentScore: 72,
    sentiment: "positive",
    tags: ["billing", "refund"],
    processedAt: "2026-03-06T09:20:00Z",
    transcriptText: `Agent: Thank you for calling support, this is Sarah. How can I help you today?\nCustomer: Hi, I noticed an extra charge of $49.99 on my account this month and I have no idea what it's for.\nAgent: I'm sorry to hear that. Let me pull up your account right away.\nCustomer: I've been a customer for 3 years and this has never happened before.\nAgent: I can see the charge — it looks like a duplicate subscription was created when you updated your payment method last week. I'll reverse that charge immediately.\nCustomer: Oh, that's a relief. When will I see the refund?\nAgent: It will appear on your account within 3-5 business days. Is there anything else I can help you with?\nCustomer: No, that's all. Thank you so much.\nAgent: Of course! Have a great day.`,
  },
  {
    callId: "call-002",
    timestamp: "2026-03-06T09:45:00Z",
    agentId: "agent-002",
    agentName: "Marcus Johnson",
    duration: 518,
    summary: [
      "Customer unable to access account after password reset failure.",
      "Agent escalated to Tier 2 after 8 minutes; issue resolved with identity verification reset.",
      "Call took 2x longer than average due to failure to use account lookup shortcut.",
    ],
    agentScore: 6,
    improvement: "Use the admin account lookup tool before attempting manual password resets to cut handle time.",
    keywords: ["password", "reset", "locked", "access", "account"],
    sentimentScore: 48,
    sentiment: "neutral",
    tags: ["account", "technical"],
    processedAt: "2026-03-06T09:56:00Z",
    transcriptText: `Agent: Support line, Marcus speaking. What can I do for you?\nCustomer: I can't get into my account. I tried resetting my password twice and it's not working.\nAgent: I'm sorry about that. Can I get your email address?\nCustomer: It's john.doe@email.com\nAgent: Okay, I see your account. Let me try a manual reset.\nCustomer: I've been locked out for two days now. This is really frustrating.\nAgent: I understand. Let me escalate this to our Tier 2 team who has deeper access.\nCustomer: Fine, but I hope this gets resolved today.\nAgent: Absolutely, they'll contact you within the hour.`,
  },
  {
    callId: "call-003",
    timestamp: "2026-03-06T10:15:00Z",
    agentId: "agent-003",
    agentName: "Priya Patel",
    duration: 284,
    summary: [
      "Customer requested cancellation citing price concerns after 2 years.",
      "Agent offered a 20% discount for 6 months; customer accepted and retained.",
      "Excellent retention execution — no compliance flags.",
    ],
    agentScore: 10,
    improvement: "Already performing at a high standard. Continue using this retention script as a model.",
    keywords: ["cancel", "retention", "discount", "price", "upgrade"],
    sentimentScore: 85,
    sentiment: "positive",
    tags: ["retention", "discount"],
    processedAt: "2026-03-06T10:22:00Z",
    transcriptText: `Agent: Hello, this is Priya. How can I help you?\nCustomer: I'm thinking about canceling my subscription. It's just gotten too expensive.\nAgent: I completely understand. May I ask what plan you're on currently?\nCustomer: The Professional tier at $120 a month.\nAgent: I really appreciate your loyalty over the past two years. I'd like to offer you our loyalty rate — 20% off for the next 6 months. That would bring you to $96 a month.\nCustomer: Hmm, that's actually pretty reasonable.\nAgent: And you'd keep all your current features. Would that work for you?\nCustomer: Yeah, let's do that. I'll stay.\nAgent: Wonderful! I've applied the discount. You'll see it on your next invoice.`,
  },
  {
    callId: "call-004",
    timestamp: "2026-03-06T10:48:00Z",
    agentId: "agent-004",
    agentName: "James O'Brien",
    duration: 621,
    summary: [
      "Customer reported product defect — item arrived damaged with missing components.",
      "Agent processed replacement order and issued prepaid return label.",
      "Failed to log the defect in the quality tracking system as required by SOP.",
    ],
    agentScore: 7,
    improvement: "Always log product defects in the quality tracking system before ending the call — it's a required SOP step.",
    keywords: ["damaged", "defect", "replacement", "return", "shipping"],
    sentimentScore: 55,
    sentiment: "neutral",
    tags: ["quality", "returns", "compliance"],
    processedAt: "2026-03-06T11:02:00Z",
  },
  {
    callId: "call-005",
    timestamp: "2026-03-06T11:20:00Z",
    agentId: "agent-005",
    agentName: "Aisha Williams",
    duration: 195,
    summary: [
      "Customer inquired about upgrading from Basic to Business plan.",
      "Agent walked through feature comparison and closed the upgrade in under 4 minutes.",
      "No upsell flag — excellent conversion execution.",
    ],
    agentScore: 9,
    improvement: "Consider mentioning the annual billing option for 2-month savings when closing upgrades.",
    keywords: ["upgrade", "business", "features", "pricing", "annual"],
    sentimentScore: 91,
    sentiment: "positive",
    tags: ["sales", "upgrade"],
    processedAt: "2026-03-06T11:28:00Z",
  },
  {
    callId: "call-006",
    timestamp: "2026-03-06T11:55:00Z",
    agentId: "agent-001",
    agentName: "Sarah Chen",
    duration: 445,
    summary: [
      "Customer complained about slow response times from the technical support email queue.",
      "Agent apologized and escalated to a priority ticket; customer received callback within 2 hours.",
      "Missed chance to offer chat support as a faster alternative channel.",
    ],
    agentScore: 7,
    improvement: "Always offer live chat as an alternative when customers report slow email support response times.",
    keywords: ["slow", "support", "email", "response", "escalation"],
    sentimentScore: 42,
    sentiment: "negative",
    tags: ["support", "escalation"],
    processedAt: "2026-03-06T12:05:00Z",
  },
  {
    callId: "call-007",
    timestamp: "2026-03-06T12:30:00Z",
    agentId: "agent-002",
    agentName: "Marcus Johnson",
    duration: 378,
    summary: [
      "Customer requested data export in CSV format for compliance audit.",
      "Agent guided customer through the self-serve export tool successfully.",
      "Could have proactively mentioned the PDF export option for audit-ready formatting.",
    ],
    agentScore: 8,
    improvement: "Mention PDF export as a compliance-ready format when customers request data for audits.",
    keywords: ["export", "data", "compliance", "CSV", "audit"],
    sentimentScore: 68,
    sentiment: "positive",
    tags: ["compliance", "data"],
    processedAt: "2026-03-06T12:40:00Z",
  },
  {
    callId: "call-008",
    timestamp: "2026-03-06T13:10:00Z",
    agentId: "agent-003",
    agentName: "Priya Patel",
    duration: 512,
    summary: [
      "Customer reported unauthorized login activity on their account from an unknown IP.",
      "Agent immediately locked the account, triggered security review, and issued temporary credentials.",
      "Compliance: Incident report filed correctly and within the required 1-hour SLA.",
    ],
    agentScore: 10,
    improvement: "Perfect execution on a security incident. Use this call as a training reference.",
    keywords: ["unauthorized", "security", "login", "breach", "locked"],
    sentimentScore: 60,
    sentiment: "neutral",
    tags: ["security", "compliance"],
    processedAt: "2026-03-06T13:22:00Z",
  },
  {
    callId: "call-009",
    timestamp: "2026-03-06T13:45:00Z",
    agentId: "agent-004",
    agentName: "James O'Brien",
    duration: 730,
    summary: [
      "Customer frustrated after being transferred 3 times before reaching the right department.",
      "Agent apologized and resolved the billing issue directly without further transfers.",
      "Call handle time inflated due to unnecessary hold while consulting a colleague instead of using the knowledge base.",
    ],
    agentScore: 5,
    improvement: "Use the internal knowledge base first before placing customers on hold for colleague consultation.",
    keywords: ["transfer", "hold", "billing", "frustrated", "wait"],
    sentimentScore: 28,
    sentiment: "negative",
    tags: ["billing", "escalation"],
    processedAt: "2026-03-06T14:00:00Z",
  },
  {
    callId: "call-010",
    timestamp: "2026-03-06T14:20:00Z",
    agentId: "agent-005",
    agentName: "Aisha Williams",
    duration: 226,
    summary: [
      "New customer onboarding call — setup assistance for API integration.",
      "Agent walked through authentication setup and provided documentation links.",
      "No issues flagged; excellent first-call experience for a new customer.",
    ],
    agentScore: 9,
    improvement: "Offer to schedule a follow-up check-in call for new API customers 48 hours post-setup.",
    keywords: ["API", "integration", "setup", "onboarding", "authentication"],
    sentimentScore: 88,
    sentiment: "positive",
    tags: ["onboarding", "technical"],
    processedAt: "2026-03-06T14:28:00Z",
  },
  {
    callId: "call-011",
    timestamp: "2026-03-05T09:00:00Z",
    agentId: "agent-001",
    agentName: "Sarah Chen",
    duration: 389,
    summary: [
      "Customer requested invoice history for tax filing purposes.",
      "Agent emailed 12 months of invoices and explained how to access them directly.",
      "Opportunity to upsell automated accounting integration was not taken.",
    ],
    agentScore: 8,
    improvement: "When customers request invoice history for accounting, mention the QuickBooks/Xero integration.",
    keywords: ["invoice", "tax", "history", "billing", "accounting"],
    sentimentScore: 74,
    sentiment: "positive",
    tags: ["billing", "accounting"],
    processedAt: "2026-03-05T09:12:00Z",
  },
  {
    callId: "call-012",
    timestamp: "2026-03-05T10:30:00Z",
    agentId: "agent-002",
    agentName: "Marcus Johnson",
    duration: 580,
    summary: [
      "Customer experiencing intermittent outage affecting 5 user accounts.",
      "Agent opened a P2 incident ticket but failed to confirm affected user list.",
      "Customer had to call back to provide the user list, creating a second unnecessary contact.",
    ],
    agentScore: 5,
    improvement: "Always collect the full list of affected users before closing an outage ticket to prevent repeat contacts.",
    keywords: ["outage", "incident", "affected", "users", "downtime"],
    sentimentScore: 31,
    sentiment: "negative",
    tags: ["technical", "outage"],
    processedAt: "2026-03-05T10:44:00Z",
  },
  {
    callId: "call-013",
    timestamp: "2026-03-05T11:15:00Z",
    agentId: "agent-003",
    agentName: "Priya Patel",
    duration: 312,
    summary: [
      "Customer requested adding 3 new team members to their Business account.",
      "Agent processed the seat additions and confirmed pro-rated billing.",
      "Successfully upsold annual commitment for the additional seats at a 15% discount.",
    ],
    agentScore: 10,
    improvement: "Excellent upsell execution. Consider sharing this call in team training.",
    keywords: ["seats", "team", "add", "billing", "annual"],
    sentimentScore: 93,
    sentiment: "positive",
    tags: ["sales", "expansion"],
    processedAt: "2026-03-05T11:22:00Z",
  },
  {
    callId: "call-014",
    timestamp: "2026-03-05T13:00:00Z",
    agentId: "agent-004",
    agentName: "James O'Brien",
    duration: 498,
    summary: [
      "Customer threatening churn after a feature they relied on was deprecated.",
      "Agent explained the migration path to the new equivalent feature.",
      "Customer remained uncertain; no escalation to retention specialist was offered.",
    ],
    agentScore: 6,
    improvement: "When a customer expresses strong dissatisfaction over a product change, escalate to a retention specialist.",
    keywords: ["deprecated", "feature", "migration", "cancel", "churn"],
    sentimentScore: 35,
    sentiment: "negative",
    tags: ["product", "retention"],
    processedAt: "2026-03-05T13:12:00Z",
  },
  {
    callId: "call-015",
    timestamp: "2026-03-05T14:30:00Z",
    agentId: "agent-005",
    agentName: "Aisha Williams",
    duration: 185,
    summary: [
      "Customer asked about GDPR data deletion request procedures.",
      "Agent provided the correct process and submitted the request on the customer's behalf.",
      "Compliance: GDPR request logged correctly within required SLA.",
    ],
    agentScore: 9,
    improvement: "Confirm the customer's email for the deletion confirmation receipt before ending the call.",
    keywords: ["GDPR", "deletion", "compliance", "data", "privacy"],
    sentimentScore: 70,
    sentiment: "positive",
    tags: ["compliance", "GDPR"],
    processedAt: "2026-03-05T14:38:00Z",
  },
  {
    callId: "call-016",
    timestamp: "2026-03-04T09:30:00Z",
    agentId: "agent-001",
    agentName: "Sarah Chen",
    duration: 420,
    summary: [
      "Enterprise customer requested a dedicated account manager.",
      "Agent confirmed eligibility and initiated the account manager assignment process.",
      "No upsell flag — appropriately handled tier escalation.",
    ],
    agentScore: 9,
    improvement: "Mention the white-glove onboarding available to Enterprise tier when confirming account manager assignment.",
    keywords: ["enterprise", "account manager", "dedicated", "tier", "escalation"],
    sentimentScore: 80,
    sentiment: "positive",
    tags: ["enterprise", "account management"],
    processedAt: "2026-03-04T09:42:00Z",
  },
  {
    callId: "call-017",
    timestamp: "2026-03-04T11:00:00Z",
    agentId: "agent-002",
    agentName: "Marcus Johnson",
    duration: 654,
    summary: [
      "Customer reported a bug causing data exports to fail silently.",
      "Agent logged the bug but could not reproduce the issue and closed the ticket.",
      "Customer called back the next day with the same issue — first-call resolution failed.",
    ],
    agentScore: 4,
    improvement: "Never close a bug ticket without either reproducing the issue or escalating to engineering — silent failures require engineering review.",
    keywords: ["bug", "export", "fail", "reproduce", "engineering"],
    sentimentScore: 22,
    sentiment: "negative",
    tags: ["technical", "bug"],
    processedAt: "2026-03-04T11:18:00Z",
  },
  {
    callId: "call-018",
    timestamp: "2026-03-04T13:20:00Z",
    agentId: "agent-003",
    agentName: "Priya Patel",
    duration: 268,
    summary: [
      "Customer asked how to set up two-factor authentication for their team.",
      "Agent walked through the admin panel setup step by step.",
      "Proactively mentioned security best practices — excellent advisory tone.",
    ],
    agentScore: 9,
    improvement: "Offer a security audit checklist as a follow-up resource when helping admins set up 2FA.",
    keywords: ["2FA", "security", "authentication", "admin", "setup"],
    sentimentScore: 87,
    sentiment: "positive",
    tags: ["security", "setup"],
    processedAt: "2026-03-04T13:28:00Z",
  },
  {
    callId: "call-019",
    timestamp: "2026-03-04T14:45:00Z",
    agentId: "agent-004",
    agentName: "James O'Brien",
    duration: 843,
    summary: [
      "Long call with confused customer trying to understand how reporting features work.",
      "Agent eventually resolved the confusion but took 14 minutes due to unclear explanations.",
      "Customer had to ask the same question 3 times — agent should have used screen share.",
    ],
    agentScore: 4,
    improvement: "Offer screen share or send a Loom walkthrough link when a customer asks the same question more than twice.",
    keywords: ["reporting", "confused", "tutorial", "walkthrough", "long"],
    sentimentScore: 45,
    sentiment: "neutral",
    tags: ["support", "training"],
    processedAt: "2026-03-04T15:02:00Z",
  },
  {
    callId: "call-020",
    timestamp: "2026-03-04T15:30:00Z",
    agentId: "agent-005",
    agentName: "Aisha Williams",
    duration: 198,
    summary: [
      "Customer wanted to understand the difference between Business and Enterprise plans.",
      "Agent gave a clear, concise comparison and scheduled a demo for Enterprise features.",
      "Strong sales handling — demo scheduled increases conversion probability significantly.",
    ],
    agentScore: 10,
    improvement: "Send a comparison PDF immediately after the call to reinforce the demo scheduling.",
    keywords: ["enterprise", "business", "comparison", "demo", "features"],
    sentimentScore: 90,
    sentiment: "positive",
    tags: ["sales", "enterprise"],
    processedAt: "2026-03-04T15:38:00Z",
  },
];

export function getMockAnalytics(): AnalyticsResponse {
  return {
    sentimentByDay: [
      { date: "2026-02-28", sentimentScore: 62, callCount: 18 },
      { date: "2026-03-01", sentimentScore: 58, callCount: 22 },
      { date: "2026-03-02", sentimentScore: 71, callCount: 15 },
      { date: "2026-03-03", sentimentScore: 65, callCount: 20 },
      { date: "2026-03-04", sentimentScore: 56, callCount: 25 },
      { date: "2026-03-05", sentimentScore: 63, callCount: 23 },
      { date: "2026-03-06", sentimentScore: 68, callCount: 10 },
    ],
    scoreByAgent: [
      { agentId: "agent-001", agentName: "Sarah Chen", avgScore: 8.2, callCount: 4, avgSentiment: 67 },
      { agentId: "agent-002", agentName: "Marcus Johnson", avgScore: 5.8, callCount: 4, avgSentiment: 42 },
      { agentId: "agent-003", agentName: "Priya Patel", avgScore: 9.8, callCount: 4, avgSentiment: 86 },
      { agentId: "agent-004", agentName: "James O'Brien", avgScore: 5.5, callCount: 4, avgSentiment: 41 },
      { agentId: "agent-005", agentName: "Aisha Williams", avgScore: 9.4, callCount: 4, avgSentiment: 88 },
    ],
    topKeywords: [
      { keyword: "billing", count: 6 },
      { keyword: "refund", count: 4 },
      { keyword: "upgrade", count: 4 },
      { keyword: "cancel", count: 3 },
      { keyword: "security", count: 3 },
      { keyword: "export", count: 3 },
      { keyword: "compliance", count: 3 },
      { keyword: "account", count: 5 },
      { keyword: "enterprise", count: 3 },
      { keyword: "support", count: 4 },
    ],
    categories: [
      { category: "Billing & Payments", count: 6 },
      { category: "Technical Issues", count: 5 },
      { category: "Sales & Upgrades", count: 4 },
      { category: "Account Access", count: 2 },
      { category: "Compliance & Security", count: 3 },
    ],
  };
}
